export const productModules = {
  produtos: {
    label: 'Produtos',
    eyebrow: 'CATÁLOGO',
    description: 'Organize seus produtos e acompanhe o que está pronto para vender.',
    emptyTitle: 'Seu primeiro produto começa aqui',
    emptyDescription: 'Crie um produto digital, salve o rascunho e publique seu primeiro checkout.',
    action: 'Criar produto',
    sprint: 2,
  },
  pedidos: {
    label: 'Pedidos',
    eyebrow: 'OPERAÇÃO',
    description: 'Acompanhe cada pedido desde a geração do PIX até a aprovação.',
    emptyTitle: 'Nenhum pedido por enquanto',
    emptyDescription: 'Quando o checkout estiver publicado, os pedidos aparecerão nesta lista.',
    action: 'Conhecer o fluxo',
    sprint: 3,
  },
  temas: {
    label: 'Temas',
    eyebrow: 'EXPERIÊNCIA',
    description: 'Construa uma identidade de checkout consistente com a sua marca.',
    emptyTitle: 'Crie a aparência do seu checkout',
    emptyDescription: 'Configure cores, logo, banner e as seções do seu primeiro layout.',
    action: 'Criar tema',
    sprint: 2,
  },
  'order-bumps': {
    label: 'Order bumps',
    eyebrow: 'CONVERSÃO',
    description: 'Aumente o ticket médio com ofertas complementares relevantes.',
    emptyTitle: 'Nenhuma oferta complementar',
    emptyDescription: 'Order bumps reutilizáveis entram na fase de otimização da conversão.',
    action: 'Planejar oferta',
    sprint: 7,
  },
  fretes: {
    label: 'Fretes',
    eyebrow: 'LOGÍSTICA',
    description: 'Defina regras de entrega para produtos físicos.',
    emptyTitle: 'Nenhuma regra de frete',
    emptyDescription: 'O módulo será habilitado junto ao suporte para produtos físicos.',
    action: 'Ver roadmap',
    sprint: 7,
  },
  pixels: {
    label: 'Pixels e tracking',
    eyebrow: 'ATRIBUIÇÃO',
    description: 'Centralize pixels, CAPI e parâmetros de campanha.',
    emptyTitle: 'Nenhum pixel conectado',
    emptyDescription: 'As integrações de conversão serão ativadas sem duplicar eventos.',
    action: 'Adicionar pixel',
    sprint: 7,
  },
  gateways: {
    label: 'Gateways',
    eyebrow: 'PAGAMENTOS',
    description: 'Conecte credenciais próprias e acompanhe a saúde das rotas.',
    emptyTitle: 'Nenhum gateway conectado',
    emptyDescription: 'O primeiro adaptador PIX real será implementado na Sprint 4.',
    action: 'Conectar gateway',
    sprint: 4,
  },
  dominios: {
    label: 'Domínios',
    eyebrow: 'PUBLICAÇÃO',
    description: 'Gerencie URLs da plataforma e domínios personalizados.',
    emptyTitle: 'Use sua marca também na URL',
    emptyDescription: 'A validação por CNAME e certificado automático chega na Sprint 8.',
    action: 'Adicionar domínio',
    sprint: 8,
  },
  webhooks: {
    label: 'Webhooks',
    eyebrow: 'AUTOMAÇÃO',
    description: 'Entregue eventos assinados aos sistemas do seu negócio.',
    emptyTitle: 'Nenhum endpoint configurado',
    emptyDescription: 'Envios, retentativas e replay auditável serão adicionados na Sprint 8.',
    action: 'Criar endpoint',
    sprint: 8,
  },
  notificacoes: {
    label: 'Notificações',
    eyebrow: 'ALERTAS',
    description: 'Escolha como receber vendas e falhas operacionais importantes.',
    emptyTitle: 'Tudo silencioso por aqui',
    emptyDescription: 'Os canais de notificação serão conectados na Sprint 8.',
    action: 'Configurar alertas',
    sprint: 8,
  },
  cobranca: {
    label: 'Cobrança',
    eyebrow: 'FINANCEIRO',
    description: 'Acompanhe comissões, saldo e faturas da plataforma.',
    emptyTitle: 'Nenhuma cobrança gerada',
    emptyDescription: 'O ledger financeiro entra depois que o ciclo de vendas estiver estável.',
    action: 'Entender cobrança',
    sprint: 9,
  },
  indicacoes: {
    label: 'Indicações',
    eyebrow: 'CRESCIMENTO',
    description: 'Convide novos negócios e acompanhe suas comissões.',
    emptyTitle: 'Seu link de indicação está a caminho',
    emptyDescription: 'O programa de parceiros será aberto na Sprint 10.',
    action: 'Ver programa',
    sprint: 10,
  },
  premios: {
    label: 'Premiações',
    eyebrow: 'CONQUISTAS',
    description: 'Acompanhe os marcos de volume da sua operação.',
    emptyTitle: 'A primeira meta começa na primeira venda',
    emptyDescription: 'As conquistas serão calculadas a partir do volume processado.',
    action: 'Ver metas',
    sprint: 10,
  },
  suporte: {
    label: 'Suporte',
    eyebrow: 'AJUDA',
    description: 'Encontre respostas e fale com o time quando precisar.',
    emptyTitle: 'Como podemos ajudar?',
    emptyDescription: 'A central de ajuda acompanhará os principais fluxos da plataforma.',
    action: 'Abrir central',
    sprint: 10,
  },
  configuracoes: {
    label: 'Configurações',
    eyebrow: 'CONTA E WORKSPACE',
    description: 'Mantenha seus dados de perfil e a identidade do workspace atualizados.',
    emptyTitle: '',
    emptyDescription: '',
    action: '',
    sprint: 1,
  },
} as const;

export type ProductModuleSlug = keyof typeof productModules;

export function isProductModule(value: string): value is ProductModuleSlug {
  return value in productModules;
}
